### ISSUE TITLE
udpproxy.exe fails to start without x64 version of visual c++

### ISSUE THREAD

**Issue by chickenbellyfin** [Griffon26/taserver#104]
By following the document instructions, udpproxy fails to start with the following error message (when run directly from cmd):
`
The code execution cannot proceed because MSVCP140.dll was not found. Reinstalling the program may fix this problem.
The code execution cannot proceed because VCRUNTIME140.dll was not found. Reinstalling the program may fix this problem.
`
Installing the x64 version of visual c++ fixes the issue, however the documentation says that x86 is required.

The firewall script fails silently when udpproxy.exe fails to start, we see this as a firewall warning message in the game server launcher.

**Comment by Griffon26** [comment]
This should be fixed now. Please reopen if not.
